### ISSUE TITLE
Add Maxima session/server management

### ISSUE THREAD

**Issue by odysseus9672** [nsmith5/Maxima.jl#28]
Sometimes it is necessary to pass the Maxima executable command line arguments. For example, my Maxima install uses sbcl, and I need to pass the following to sbcl through Maxima: `maxima -X '--dynamic-space-size 4096'`. This allows for me to modify the size of the sbcl stack, speeding up some scripts and preventing crashes in others.

I tried to do a minor addition in [a fork](https://github.com/odysseus9672/Maxima.jl), but found that trying to modify the modules `ms` variable crashed. Thus, this will require an expansion of the session management api, giving the user the ability to stop, start, and restart Maxima sessions in order to accommodate this sort of argument passing.

**Comment by chakravala** [comment]
It is already possible to restart a maxima session using the `Maxima.Reset()` functionality I implemented

**Comment by odysseus9672** [comment]
Excellent! I've updated the fork to add the `ArgString` functionality to your `Load` and `Reset` functions, and it appears to work.

**Comment by nsmith5** [comment]
Yeah, looking at your branch you've got the idea. Open a pull request and I'll review. Please take into consideration my comment on your other issue (Maxima.jl is not and will not target 0.7 until it is released)
