### ISSUE TITLE
Incorrect syntax error of print() 

### ISSUE THREAD

**Issue by sunnsi** [nsmith5/Maxima.jl#42]
Hi, I fond another issue shown below.
The reason for the error seems to be the repeated printings of the expression in wxmaxima or xmaxima. 
```julia
maxima> f(x):=3e-4*3*x^2+x+x+x;
                                          2
                        f(x) := 0.3e-3 3 x  + x + x + x
maxima> ratprint:false;
                                     false
maxima> print(f(x));
┌ Warning: Invalid Maxima expression
└ @ Maxima ~/.julia/packages/Maxima/p6qVJ/src/io.jl:21
 
incorrect syntax: 9.e-4 is not an infix operator
.9e-3*x^2+3*x0.9e-3*
```

**Comment by nsmith5** [comment]
Hmm, yeah things that are display related conflict with how Maxima.jl is working under the hood. `print(f(x))` here is trying to write to stdout but Maxima.jl is talking to Maxima over a pipe so writing to stdout conflicts with that communication. Perhaps this should be mentioned in the docs, but I'm not sure I see this behaviour as really limiting. What are you trying to do?

**Comment by sunnsi** [comment]
Dear Nathan, thanks for your reply. I am trying to solve a non-linear equation as an intermediate step in a program and want to check its result. Now  I have tried julia way to solve the equation. Thanks all the same for the excellent package.

**Comment by nsmith5** [comment]
Ok, I'm labelling this as `wontfix` for now unless I see a pressing need to change this.

To be clear though, there are plenty of ways around this problem. For instance switching back to julia
```julia
maxima> f(x) := x^2 + x + 1;
 
                                       2
                              f(x) := x  + x + 1

julia> print(mcall(m"f(x)"))
x^2+x+1
```

I'm glad to hear you're using (or at least tried to use) Maxima.jl for this. Doing intermediate symbolic math in numerical computations is exactly why this was created!

**Comment by sunnsi** [comment]
Thanks, Nathan.
The main problem I met was the following one, "solve()" function in mcall() does not give the same result as in the original maxima. Its result will be taken in later calculations in julia.   I tried to figure out the reason.

```julia
julia> using Maxima

julia> m"assume(Ci>0, area>0, v>0)"
 
                        assume(Ci > 0, area > 0, v > 0)

julia> m"Fa(D) := area-Ci*sqrt(D*v*F/R/T)*10^(3.87)"
 
                                             D v F
                                             -----
                                               R      3.87
                     Fa(D) := area - Ci sqrt(-----) 10
                                               T

julia> MExpr("solve(Fa(D),D)")|>mcall
 
                                  [Fa(D) = 0]

julia> mcall(m"ratprint:false")
 
                                     false

julia> mcall(m"solve(Fa(D),D)")
 
                                  [Fa(D) = 0]

maxima> assume(Ci>0, area>0, v>0);
 
                           [Ci > 0, area > 0, v > 0]

maxima> Fa(D) := area-Ci*sqrt(D*v*F/R/T)*10^(3.87);
 
                                             D v F
                                             -----
                                               R      3.87
                     Fa(D) := area - Ci sqrt(-----) 10
                                               T

maxima> solve(Fa(D),D);
 
                                                   2
                               39355814689 R T area
                       [D = ---------------------------]
                                                  2
                            2162762879557182016 Ci  F v

```
