### ISSUE TITLE
string result

### ISSUE THREAD

**Issue by jmarcellopereira** [nsmith5/Maxima.jl#8]
The code:
b = mcall("mnewton([x*y - 2*x^3, -x^2 + 8*y - 2], [x, y], [5, 5])")
"[[x=0.3651483716701107,y=0.2666666666666666]]"

typeof(b)
String

What is the best way to transform into a vector?

**Comment by nsmith5** [comment]
The string result here is not actually a bug. As a standard all the functions in Maxima try to return the type that was given to them if possible. You called mcall with a string and so you get a string back. For example:

```julia
julia> mcall("mnewton([x*y - 2*x^3, -x^2 + 8*y - 2], [x, y], [5, 5])")
"[[x=0.3651483716701107,y=0.2666666666666667]]"

julia> typeof(ans)
Sting

julia> mcall(m"mnewton([x*y - 2*x^3, -x^2 + 8*y - 2], [x, y], [5, 5])")
 
              [[x = 0.3651483716701107, y = 0.2666666666666667]]

julia> typeof(ans)
Maxima.MExpr

julia> mcall(:(expand((x + y)^2)))
:(y ^ 2 + 2 * x * y + x ^ 2)

julia> typeof(ans)
Expr
```
Getting a vector out of this is an issue though. I'll look into wrapping `getindex` from the julia standard library and `rhs` and `lhs` from Maxima to make something like the following possible:

```julia
julia> using Maxima

julia> mcall(m"load(mnewton)")

julia> b = mcall(m"mnewton([x*y - 2x^3, -x^2 + 8*y - 2], [x, y], [5, 5])")

julia> x = rhs(b[1][1])

julia> y = rhs(b[1][2])
```

That said, if you want a fix for right now, you can use string parsing to get to your final solution:

```julia
julia> b = "[[x=0.3651483716701107,y=0.2666666666666667]]"
"[[x=0.3651483716701107,y=0.2666666666666667]]"

julia> b = replace(b, "x=", "")
"[[0.3651483716701107,y=0.2666666666666667]]"

julia> b = replace(b, "y=", "")
"[[0.3651483716701107,0.2666666666666667]]"

julia> z = eval(parse(b))[1]
2-element Array{Float64,1}:
 0.365148
 0.266667
```

**Comment by jmarcellopereira** [comment]
Hi Smith, thanks for this  ;)
I used it that way and it worked: 

sol_sis = mcall("mnewton([x*y - 2*x^3, -x^2 + 8*y - 2], [x, y], [5, 5])")

##### print only y
eval(parse(sol_sis))[1][2]
0.2666666666666666
